### ISSUE TITLE
Bottom gap after pushing view with keyboard open

### ISSUE THREAD

**Issue by SystemKeeper** [Ivansss/SlackTextViewController#6]
![image](https://user-images.githubusercontent.com/1580193/100814584-4a104c00-3442-11eb-825c-b26c558914a9.png)

**How to reproduce**

* Go into room
* Open keyboard
* Open room information (tap on room name)
* Leave room information
* Close keyboard

**Workaround**

https://github.com/Ivansss/SlackTextViewController/blob/6dac276400bbb7cb884b33a7f343d99fa2f28858/Source/SLKTextViewController.m#L241-L257

This code should prevent the gap at the bottom. I did a short test and the following condition was never true
https://github.com/Ivansss/SlackTextViewController/blob/6dac276400bbb7cb884b33a7f343d99fa2f28858/Source/SLKTextViewController.m#L252
because the `textInputContentFrame` height was always 0

Changing this to just `if (textInputBackgroudView)` worked for me. Not sure, why the  `> 0` check was there ?!
Maybe checking if `UIToolbarContentView` was found at all would be safer.

I'm also not sure if this would lead to adding `safeAreaInsets` multiple times, if the subviews get layouted multiple times. Maybe we could just do `textInputBackgroudViewFrame.size.height = self.view.safeAreaInsets.bottom;`.

Let me know what you think and if you would like a PR.

**Comment by SystemKeeper** [comment]
> I'm also not sure if this would lead to adding safeAreaInsets multiple times, if the subviews get layouted multiple times. Maybe we could just do textInputBackgroudViewFrame.size.height = self.view.safeAreaInsets.bottom;.

Read that wrong, shouldn’t be a problem.

**Comment by Ivansss** [comment]
Interesting! I forgot to add the source of this workaround :S
So it seems that there is no "UIToolbarContentView" subview.

And for some reason it doesn'tmatter what frame you set in 
`[textInputBackgroudView setFrame: textInputBackgroudViewFrame];`

You could even set
`[textInputBackgroudView setFrame: CGRectZero];`

and the gap bug is fixed and the toolbar is displayed correctly. :S

**Comment by SystemKeeper** [comment]
> You could even set
[textInputBackgroudView setFrame: CGRectZero];

and the gap bug is fixed and the toolbar is displayed correctly. :S

Interesting ... haven’t tested this, but I mean... if it works ... ;)
